name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/actions-dotnet@v3
      with:
        dotnet-version: '10.0.x' # Match this to your specific .NET version

    - name: Build Project (Release & Debug)
      run: |
        dotnet build -c Release

    - name: Upload Clean Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-Application-Release
        path: ./code/output.AnyCPU.Release/        
