name: .NET Desktop Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v5

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '10.0.x'

    - name: Build Project (Release)
      working-directory: ./code
      run: |
        dotnet build -c Release

    - name: Upload Clean Build Artifacts
      uses: actions/upload-artifact@v5
      with:
        name: Menu-test.output.AnyCPU.Debug.zip
        path: ./code/output.AnyCPU.Release/
